version: "3.8"

services:
  bdpostgres:
    image: postgres:14
    restart: always
    ports:
      - "5555:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_BD=BDAssistance
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "85:80"
    depends_on:
      - bdpostgres

volumes:
  postgres-data:
